# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wifi < Formula
  desc "Cross-platform WiFi diagnostic CLI tool"
  homepage "https://github.com/okisdev/wifi"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okisdev/wifi/releases/download/v0.1.1/wifi_0.1.1_darwin_amd64.tar.gz"
      sha256 "036259d576f8e56bcfbd0b16c5402c77efdb3fcb10e1ba9c8ab3f853cbeae984"

      define_method(:install) do
        bin.install "wifi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okisdev/wifi/releases/download/v0.1.1/wifi_0.1.1_darwin_arm64.tar.gz"
      sha256 "68ab840cd9cabb2e717433b7d236f463dce284152ef2b0bb93e16da33d06e3fe"

      define_method(:install) do
        bin.install "wifi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/okisdev/wifi/releases/download/v0.1.1/wifi_0.1.1_linux_amd64.tar.gz"
      sha256 "e9cc2dcd3e9359a3e4d3eed7ce394c66c5d242618cc58d9f626901c03140fbb1"
      define_method(:install) do
        bin.install "wifi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okisdev/wifi/releases/download/v0.1.1/wifi_0.1.1_linux_arm64.tar.gz"
      sha256 "0e7502b34b175f0bdbb05c6ee66102639a15ebfa21ef5de38759a008347e16c8"
      define_method(:install) do
        bin.install "wifi"
      end
    end
  end

  test do
    system "#{bin}/wifi", "version"
  end
end
