# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wifi < Formula
  desc "Cross-platform WiFi diagnostic CLI tool"
  homepage "https://github.com/okisdev/wifi"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okisdev/wifi/releases/download/v0.1.0/wifi_0.1.0_darwin_amd64.tar.gz"
      sha256 "dc9c1b39f01bc0535a56d505b055e6d7ca6b1035c2ce19d94cbf7f0d8ec59add"

      define_method(:install) do
        bin.install "wifi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okisdev/wifi/releases/download/v0.1.0/wifi_0.1.0_darwin_arm64.tar.gz"
      sha256 "30c41b557b96f04791d748555bcb1aeb28abd2325b51eb32c52b379bda3d475a"

      define_method(:install) do
        bin.install "wifi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/okisdev/wifi/releases/download/v0.1.0/wifi_0.1.0_linux_amd64.tar.gz"
      sha256 "ad7421fa37f5d91fec543b6425a3a310b40ee654ac3aa774072af6328479d5d7"
      define_method(:install) do
        bin.install "wifi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okisdev/wifi/releases/download/v0.1.0/wifi_0.1.0_linux_arm64.tar.gz"
      sha256 "8ff59c2b1239c0ee3970d5e37913a978f27a69037cd1c86b9469dc5c70231482"
      define_method(:install) do
        bin.install "wifi"
      end
    end
  end

  test do
    system "#{bin}/wifi", "version"
  end
end
